# @Per-app effects

# foot terminal
for_window [app_id="foot"] opacity 0.75, blur enable
# kitty terminal 
for_window [app_id="kitty"] opacity 0.75, blur enable

# @Per-layer effects
layer_effects "waybar" blur enable
layer_effects "mako" blur enable; corner_radius 8
